### ISSUE TITLE
Cannot find module 'ws'

### ISSUE THREAD

**Issue by UltraTempest** [dferber90/jsdom-screenshot#24]
Getting the following error after following the guide: https://gist.github.com/dferber90/6fe76cde582b8746191478fac34c8b7d

```
Test suite failed to run

    Cannot find module 'ws' from '../../node_modules/jsdom-screenshot/node_modules/puppeteer/lib/WebSocketTransport.js'

    Require stack:
      /Users/omaranshasi/Code/cygnus-stack/node_modules/jsdom-screenshot/node_modules/puppeteer/lib/WebSocketTransport.js
      /Users/omaranshasi/Code/cygnus-stack/node_modules/jsdom-screenshot/node_modules/puppeteer/lib/Launcher.js
      /Users/omaranshasi/Code/cygnus-stack/node_modules/jsdom-screenshot/node_modules/puppeteer/lib/Puppeteer.js
      /Users/omaranshasi/Code/cygnus-stack/node_modules/jsdom-screenshot/node_modules/puppeteer/lib/api.js
      /Users/omaranshasi/Code/cygnus-stack/node_modules/jsdom-screenshot/node_modules/puppeteer/index.js
      /Users/omaranshasi/Code/cygnus-stack/node_modules/jsdom-screenshot/generateImage.js
      /Users/omaranshasi/Code/cygnus-stack/node_modules/jsdom-screenshot/index.js
      src/components/__tests__/testUtils.jsx
      src/components/rooms/creation/bulk/__tests__/BulkImportPage.spec.jsx

      at Resolver.resolveModule (../../node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (../../node_modules/jsdom-screenshot/node_modules/puppeteer/lib/WebSocketTransport.js:16:19)
```

Any ideas how to solve it?
Thanks

**Comment by dferber90** [comment]
Unfortunately not :/

You are the first one to report this problem so I guess it might be related to your specific setup. Sorry that I can't be of more help with the info given.

You could probably "npm install ws" to work around it.
